  [1m[35m (2722.5ms)[0m  [1m[35mCREATE DATABASE "hachiouji_gomi" ENCODING = 'unicode'[0m
  [1m[35m (2051.5ms)[0m  [1m[35mCREATE DATABASE "hachiouji_gomi_test" ENCODING = 'unicode'[0m
Started GET "/" for 172.18.0.1 at 2021-12-30 00:37:04 +0900
Processing by Rails::WelcomeController#index as HTML
  Rendering /usr/local/bundle/gems/railties-6.0.4.4/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /usr/local/bundle/gems/railties-6.0.4.4/lib/rails/templates/rails/welcome/index.html.erb (Duration: 12.9ms | Allocations: 461)
Completed 200 OK in 74ms (Views: 43.6ms | ActiveRecord: 0.0ms | Allocations: 2650)


Started GET "/favicon.ico" for 172.18.0.1 at 2021-12-30 00:37:05 +0900
  
ActionController::RoutingError (No route matches [GET] "/favicon.ico"):
  
actionpack (6.0.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.4) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.4) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.4) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.4) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.4) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.4) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.4) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.4) lib/rails/engine.rb:527:in `call'
puma (4.3.10) lib/puma/configuration.rb:228:in `call'
puma (4.3.10) lib/puma/server.rb:718:in `handle_request'
puma (4.3.10) lib/puma/server.rb:472:in `process_client'
puma (4.3.10) lib/puma/server.rb:328:in `block in run'
puma (4.3.10) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for 172.18.0.1 at 2021-12-30 00:55:10 +0900
Processing by Rails::WelcomeController#index as HTML
  Rendering /usr/local/bundle/gems/railties-6.0.4.4/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /usr/local/bundle/gems/railties-6.0.4.4/lib/rails/templates/rails/welcome/index.html.erb (Duration: 4.5ms | Allocations: 181)
Completed 200 OK in 9ms (Views: 8.0ms | ActiveRecord: 0.0ms | Allocations: 881)


Started GET "/api/v1/refuse" for 172.18.0.1 at 2021-12-30 01:38:08 +0900
  
AbstractController::ActionNotFound (The action 'index' could not be found for Api::V1::RefuseController):
  
actionpack (6.0.4.4) lib/abstract_controller/base.rb:131:in `process'
actionpack (6.0.4.4) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (6.0.4.4) lib/action_controller/metal.rb:254:in `dispatch'
actionpack (6.0.4.4) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (6.0.4.4) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.4.4) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.4.4) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.4.4) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.4.4) lib/action_dispatch/routing/route_set.rb:834:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
activerecord (6.0.4.4) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.4.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.4) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.4) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.4) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.4) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.4) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.4) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.4) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.4) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.4) lib/rails/engine.rb:527:in `call'
puma (4.3.10) lib/puma/configuration.rb:228:in `call'
puma (4.3.10) lib/puma/server.rb:718:in `handle_request'
puma (4.3.10) lib/puma/server.rb:472:in `process_client'
puma (4.3.10) lib/puma/server.rb:328:in `block in run'
puma (4.3.10) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/api/v1/refuse" for 172.18.0.1 at 2021-12-30 01:39:17 +0900
Processing by Api::V1::RefuseController#index as HTML
Completed 200 OK in 0ms (Views: 0.1ms | ActiveRecord: 0.0ms | Allocations: 237)


Started GET "/api/v1/refuse" for 172.18.0.1 at 2021-12-30 01:42:44 +0900
Processing by Api::V1::RefuseController#index as HTML
Completed 200 OK in 1ms (Views: 0.4ms | ActiveRecord: 0.0ms | Allocations: 67)


Started GET "/api/v1/refuse" for 172.18.0.1 at 2021-12-30 10:27:04 +0900
Processing by Api::V1::RefuseController#index as HTML
Completed 200 OK in 0ms (Views: 0.1ms | ActiveRecord: 0.0ms | Allocations: 273)


Started GET "/api/v1/refuse" for 172.18.0.1 at 2021-12-30 12:05:18 +0900
Processing by Api::V1::RefuseController#index as HTML
Completed 200 OK in 2ms (Views: 1.3ms | ActiveRecord: 0.0ms | Allocations: 67)


Started GET "/api/v1/refuse" for 172.18.0.1 at 2021-12-30 12:30:22 +0900
Processing by Api::V1::RefuseController#index as HTML
Completed 200 OK in 0ms (Views: 0.1ms | ActiveRecord: 0.0ms | Allocations: 273)


